# Generated by Django 2.0.7 on 2020-05-09 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_details', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.OrderDetail')),
                ('ordered_item', models.ManyToManyField(blank=True, to='core.OrderItem')),
            ],
        ),
    ]
